"""Line-preserving reader/writer for VPinballX.ini.

The default ini generated by `VPinballX_BGFX -h` is used as a template: every key is present
(blank = "use the built-in default") and is preceded by a comment describing it. We keep the
template text intact and only rewrite the value of the keys the user configured.
"""
import re
from dataclasses import dataclass, field

_SECTION = re.compile(r"^\[(.+)\]\s*$")
_HEADER = re.compile(r"^(?P<label>[^:]+?):\s*(?P<help>.*?)\s*\[Default: (?P<default>.*)\]:?\s*$")
_OPTION = re.compile(r"(-?\d+)='(.*?)'(?=,\s*-?\d+='|$)")
_RANGE = re.compile(r"^(?P<value>.+?) in (?P<lo>\S+) \.\. (?P<hi>\S+)$")


@dataclass
class FieldMeta:
    """What the template comment says about a key."""
    label: str = ""
    help: str = ""
    detail: list = field(default_factory=list)   # extra comment lines below the header
    default: str = ""
    options: list = field(default_factory=list)  # [(value, label)]
    min: str = None
    max: str = None


def parse_comment(lines):
    """Parse the comment block preceding a key. Returns FieldMeta or None if unparseable."""
    if not lines:
        return None
    m = _HEADER.match(lines[0])
    if not m:
        return FieldMeta(label=lines[0], detail=lines[1:])
    meta = FieldMeta(label=m["label"], help=m["help"], detail=[l.strip() for l in lines[1:]])
    raw = m["default"].strip()
    options = _OPTION.findall(raw)
    if options:
        meta.options = [(v, label) for v, label in options]
        default_label = raw.split(",", 1)[0].strip().strip("'")
        meta.default = next((v for v, label in options if label == default_label), "")
        return meta
    r = _RANGE.match(raw)
    if r:
        meta.default, meta.min, meta.max = r["value"].strip("'"), r["lo"], r["hi"]
    else:
        meta.default = raw.strip("'")
    return meta


class IniDocument:
    def __init__(self, text):
        self.lines = text.split("\n")
        self._reindex()

    @classmethod
    def from_file(cls, path):
        with open(path, encoding="utf-8", errors="replace") as f:
            return cls(f.read())

    def _reindex(self):
        self._keys = {}       # (section, key) -> line index
        self._sections = {}   # section -> (first line, last line) inclusive
        section = None
        for i, line in enumerate(self.lines):
            m = _SECTION.match(line)
            if m:
                section = m[1]
                self._sections[section] = [i, i]
                continue
            if section is None:
                continue
            self._sections[section][1] = i
            if line.startswith(";") or "=" not in line:
                continue
            self._keys.setdefault((section, line.split("=", 1)[0].strip()), i)

    def sections(self):
        return list(self._sections)

    def keys(self, section):
        """Keys of a section, in file order."""
        return [k for (s, k), _ in sorted(self._keys.items(), key=lambda item: item[1]) if s == section]

    def has_section(self, section):
        return section in self._sections

    def has(self, section, key):
        return (section, key) in self._keys

    def get(self, section, key):
        i = self._keys.get((section, key))
        return None if i is None else self.lines[i].split("=", 1)[1].strip()

    def set(self, section, key, value):
        line = f"{key} = {value}"
        i = self._keys.get((section, key))
        if i is not None:
            self.lines[i] = line
            return
        if section not in self._sections:
            ends_with_newline = self.lines[-1] == ""
            if ends_with_newline:
                self.lines.pop()
            self.lines += ["", f"[{section}]", line] + ([""] if ends_with_newline else [])
        else:
            last = self._sections[section][1]
            while last > self._sections[section][0] and not self.lines[last].strip():
                last -= 1
            self.lines.insert(last + 1, line)
        self._reindex()

    def meta(self, section, key):
        i = self._keys.get((section, key))
        if i is None:
            return None
        block = []
        j = i - 1
        while j >= 0 and self.lines[j].startswith(";"):
            block.insert(0, self.lines[j][1:].strip())
            j -= 1
        return parse_comment(block)

    def to_text(self):
        return "\n".join(self.lines)
