#!/usr/bin/env python3
"""Add every wizard setting that the base ini lacks, with a comment in the base file's own format.

    tools/sync_base.py [path/to/ini]        (default: the project's VPinballX.ini)

The base ini is the default generated by `VPinballX_BGFX -h`, which leaves out plugin sections/keys and
other settings that VPXConfig manages. This adds them (blank value, comment with label, description and
default) so a defaults-based output puts them in the right place. It also fills in the starting answers
(`initial` of a Setting) that differ from VPX's default, so that a fresh start compares equal to the base file
and Review shows no changes. Lines that already have a value are never changed; running it again does nothing.
A backup copy is kept as <name>.vpconfigbackup when none exists yet.
Run it after adding a Setting in vpxconfig/ (a test fails until the base file has the key).
"""
import shutil
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from vpxconfig import server  # noqa: E402
from vpxconfig.generate import _same  # noqa: E402
from vpxconfig.ini import IniDocument  # noqa: E402


def comment_block(f):
    """Comment lines + blank key for one resolved field, in the format the base file (and parse_comment) uses."""
    if ":" in f["label"]:
        raise ValueError(f"{f['id']}: a label containing ':' can't be written as a base file comment ({f['label']!r})")
    if f["type"] == "select":
        default = f"'{f['default_label']}', " + ", ".join(f"{o['value']}='{o['label']}'" for o in f["options"])
    elif f["type"] == "bool":
        default = f["default"]
    elif f["min"] is not None:
        default = f"{f['default']} in {f['min']} .. {f['max']}"
    else:
        default = f"'{f['default']}'"
    return ([f"; {f['label']}: {f['help']} [Default: {default}]"] + [f";   {n}" for n in f["detail"]]
            + [f"{f['key']} = "])


def sync(text, fields):
    """Returns (new text, ids added, ids given their starting value). New plugin sections go after the last plugin section."""
    doc = IniDocument(text)

    def end_of(section):
        first, last = doc._sections[section]
        while last > first and not doc.lines[last].strip():
            last -= 1
        return last

    added = []
    for fid, f in fields.items():
        if doc.has(f["section"], f["key"]):
            continue
        if doc.has_section(f["section"]):
            at = end_of(f["section"]) + 1
            doc.lines[at:at] = [""] + comment_block(f)
        else:
            plugins = [s for s in doc.sections() if s.startswith("Plugin.")]
            at = end_of(plugins[-1]) + 1 if plugins else len(doc.lines)
            doc.lines[at:at] = ["", "", "", f"[{f['section']}]"] + comment_block(f)
        doc._reindex()
        added.append(fid)
    valued = []
    for fid, f in fields.items():
        initial = f.get("initial", "")
        if initial and not _same(initial, f["default"], f["type"]) and not (doc.get(f["section"], f["key"]) or "").strip():
            doc.set(f["section"], f["key"], initial)
            valued.append(fid)
    return doc.to_text(), added, valued


def main(argv):
    path = Path(argv[1]).expanduser() if len(argv) > 1 else server.TEMPLATE
    fields = server.App(server.TEMPLATE, "unused", Path(tempfile.mkdtemp()) / "state.json").fields
    text, added, valued = sync(path.read_text(encoding="utf-8", errors="replace"), fields)
    if not added and not valued:
        print(f"{path.name} already has every wizard setting.")
        return
    backup = path.with_name(path.name + ".vpconfigbackup")
    if not backup.exists():
        shutil.copy2(path, backup)
        print(f"backup: {backup}")
    path.write_text(text, encoding="utf-8")
    print(f"added {len(added)} setting(s) to {path.name}: " + ", ".join(added[:6]) + (" ..." if len(added) > 6 else ""))
    print(f"gave {len(valued)} setting(s) their starting value: " + ", ".join(valued))


if __name__ == "__main__":
    main(sys.argv)
